
orbs:
  terraform: circleci/terraform@3.2.1


working_directory: &working_directory ~/co-infra-cc

fingerprint : &fingerprint "Some fingerprint"
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - terraform/lint_terraform_recursive:
          context: aws-staging
          name: lint_terraform_recursive
          working_directory: *working_directory
          tag: TERRAFORM_TAG_1_1_4
      - terraform/plan:
          context: aws-staging
          name: plan_staging
          working_directory: *working_directory
          tag: TERRAFORM_TAG_1_1_4
          fingerprint: *fingerprint
          requires:
            - lint_terraform_recursive
      - terraform/plan:
          context: aws-sandbox
          name: plan_sandbox
          working_directory: *working_directory
          tag: TERRAFORM_TAG_1_1_4
          fingerprint: *fingerprint
          requires:
            - lint_terraform_recursive
      - terraform/plan:
          context: aws-production
          name: plan_production
          working_directory: *working_directory
          tag: TERRAFORM_TAG_1_1_4
          fingerprint: *fingerprint
          requires:
            - lint_terraform_recursive
      - terraform/apply:
          context: aws-staging
